# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CameraShareSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CameraShareSample
	pod 'Flurry-iOS-SDK/FlurrySDK' #Analytics Pod
	pod 'Flurry-iOS-SDK/FlurryAds' #Advertising Pod (requires Analytics)

end
